-- MySQL Script generated by MySQL Workbench
-- Wed Apr 12 17:56:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cecyt42
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cecyt42` ;

-- -----------------------------------------------------
-- Schema cecyt42
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cecyt42` DEFAULT CHARACTER SET utf8 ;
USE `cecyt42` ;

-- -----------------------------------------------------
-- Table `administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administradores` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NULL,
  `contrasena` TEXT(500) NULL,
  `nombre` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alumnos` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `grupo` VARCHAR(45) NULL,
  `semestre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignaturas` (
  `id_asignatura` INT NOT NULL AUTO_INCREMENT,
  `asignatura` VARCHAR(100) NULL,
  PRIMARY KEY (`id_asignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificaciones` (
  `id_calificacion` INT NOT NULL AUTO_INCREMENT,
  `calificacion` DOUBLE NULL,
  `id_alumno` INT NOT NULL,
  `id_asignatura` INT NOT NULL,
  PRIMARY KEY (`id_calificacion`),
    FOREIGN KEY (`id_alumno`)
    REFERENCES `alumnos` (`id_alumno`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `asignaturas` (`id_asignatura`)
      ON DELETE CASCADE
      ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
